# https://docs.gitlab.com/ce/ci/yaml/README.html

image: registry.gitlab.com/teavana/kungfu/builder:ubuntu18

stages:
- build

job1:
  stage: build

  before_script:
  - ./scripts/download-mnist.sh

  script:
  # - pip3 install --user -U .
  - ./scripts/install.sh
  - ./examples/kungfu-train.py
  - ./bin/kungfu-run -np 2 -timeout 10s python3 ./examples/kungfu-train.py --use-async-sgd=1 --n-epochs=1 --batch-size=5000 --model-name=mnist.slp
