# https://docs.gitlab.com/ce/ci/yaml/README.html

image: registry.gitlab.com/teavana/kungfu/builder:ubuntu18

stages:
- unit test
- integration test
- system test

job1:
  stage: unit test

  script:
  - |
    ./configure
    make
    make test
    go test -v ./srcs/go/rchannel

job2:
  stage: integration test
  script:
  - |
    ./scripts/run-integration-tests.sh

job3:
  stage: system test

  before_script:
  - |
    DATA_DIR=$HOME/var/data \
    DATA_MIRROR_PREFIX=https://kungfudata.blob.core.windows.net/data \
    ./scripts/download-mnist.sh

  script:
  - |
    cmake --version
    pip3 install -vvv -U .
    GOBIN=$(pwd)/bin go install -v ./srcs/go/kungfu-run
  - |
    ./examples/kungfu-train.py
  - |
    ./bin/kungfu-run -np 2 -timeout 60s \
      python3 ./examples/kungfu-train.py \
        --use-async-sgd=1 \
        --n-epochs=1 \
        --batch-size=5000 \
        --model-name=mnist.slp
