- hosts: all
  tasks:

  - name: ping test
    shell: pwd

  - name: run benchmark
    # https://docs.ansible.com/ansible/latest/modules/shell_module.html
    shell: |
      ./bin/kungfu-run \
        -np 8 \
        -m 4 \
        -timeout 120s \
        -hosts {{ ansible_play_hosts | join(',') }} \
        -self {{ inventory_hostname }} \
        python3 \
        ./examples/kungfu-train.py \
        --use-async-sgd=1 \
        --n-epochs=10 \
        --batch-size=50 \
        --model-name=mnist.mlp
    args:
      chdir: kungfu
    ignore_errors: yes
    register: result

  - name: pack logs
    shell: cd kungfu && tar -cf logs.tar *.log && bzip2 -f logs.tar

  - name: download log
    fetch:
      src: ./kungfu/logs.tar.bz2
      dest: ~/logs/

  # - debug: var=out.stdout_lines
  - debug: msg="{{ result.stdout }}"
  - debug: msg="{{ result.stderr }}"
